### ISSUE TITLE
Could you please share the dataset?

### ISSUE THREAD

**Issue by duzhenjiang113** [Rowl1ng/3Dsketch2shape#1]

**Comment by Rowl1ng** [comment]
- You can access the VR sketch dataset here: [https://cvssp.org/data/VRChairSketch/](https://cvssp.org/data/VRChairSketch/)
- The collection of 6,576 chair shapes is sourced from ShapeNetCore v2.
- The SDF files for chair shapes can be obtained from [https://github.com/Yueeey/sketcch3D](https://github.com/Yueeey/sketcch3D)

**Comment by Rowl1ng** [comment]
@duzhenjiang113 For convenience, I have uploaded the aligned sketch and shape point cloud data we used for training and inference in the paper [link](https://drive.google.com/drive/folders/10eYUtsZcCGSjj2H51EldFI5umXUmvUw0?usp=sharing). You can find the detailed usage instructions in the Readme.
