### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by Chunan-Yu** [Rowl1ng/3Dsketch2shape#2]
Hello, thank you for your work, I am very interested in your work. I have two questions that I need your help with. 
(1) I'm trying to infer your network and I need to run that file. 
(2) When I modified the inference in flow_sdf_trainer.py, I found that I need to load a ‘last_resume_ckpt’, but the pre-training model you provided in the link does not support reading. Which model should I load?

**Comment by Rowl1ng** [comment]
@YCA-eng Thank you for your interest in this work. I apologize for not having provided complete information on inference and the model earlier. I have organized the inference code, uploaded the necessary dataset and model files, and updated the Readme. I hope this will be helpful for you. If you encounter any issues, please feel free to contact me for assistance.
