### ISSUE TITLE
inference

### ISSUE THREAD

**Issue by 77waiwai-Demon** [Rowl1ng/3Dsketch2shape#3]
Very interesting work! However, I encountered issues while using the pre-trained model you provided for inference. Could you please provide a detailed inference process? Thank you.

**Comment by Rowl1ng** [comment]
@77waiwai-Demon Thank you for your praise. I'm sorry for not having updated the code promptly. I have now organized the inference section of the code along with the required data and models. You can find the specifics in the latest Readme. If you have any other questions, please feel free to contact me.
