### ISSUE TITLE
How to train AE?

### ISSUE THREAD

**Issue by Chunan-Yu** [Rowl1ng/3Dsketch2shape#4]
Hello, I want to reproduce your code, but I encountered a problem when running the first step (train_AE). How should I train the first step and where should I obtain the configuration file? I got the required latent code from deepsdf training. Is this correct?

**Comment by Rowl1ng** [comment]
@YCA-eng Sorry for the misleading information in the old version of Readme. I have updated the AE training command in latest Readme [Stage 1: Autoencoder](https://github.com/Rowl1ng/3Dsketch2shape#stage-1-autoencoder). You can either train deepsdf from scratch or use the latent code and SDF decoder checkpoint from [link](https://drive.google.com/drive/folders/10eYUtsZcCGSjj2H51EldFI5umXUmvUw0?usp=sharing) (more recommended) which are obtained from Stage 1: SDF decoder. I would suggest you pull the latest code and run the corresponding training command.
