### ISSUE TITLE
Could you please provide the access code of Baidu Netdisk of sdf files?

### ISSUE THREAD

**Issue by 2646044472** [Rowl1ng/3Dsketch2shape#5]
Could you please kindly provide the access code of Baidu Netdisk of sdf files? The link you provided to download was https://pan.baidu.com/share/init?surl=kwMeWLoN9hDMgM-XEmPMew&pwd=vuc. However, "vuc" is not the correct access code.

**Comment by Rowl1ng** [comment]
Thank you for pointing out this issue. The access code is vucd.
